import { chromium } from '@playwright/test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
const browser = await chromium.connectOverCDP('http://127.0.0.1:9223');
const pages = browser.contexts().flatMap(c=>c.pages());
const page = pages.find(p=>!p.url().startsWith('devtools:')) ?? pages[0];
page.setDefaultTimeout(15000);
await page.waitForSelector('h1');
const ipc = async(op,payload={})=>page.evaluate(async ({op,payload})=>window.__TAURI_INTERNALS__.invoke(op,payload),{op,payload});
const before=await ipc('snapshot');
if(before.tasks.length || before.catalog.tokens.length)throw Error('Native smoke expects empty data');
await page.getByRole('button',{name:'全局设置',exact:true}).click();
await page.getByRole('tab',{name:'GitHub'}).click();
await page.getByRole('button',{name:'新增 Token',exact:true}).click();
await page.getByLabel('名称',{exact:true}).fill('Native smoke');
await page.getByLabel('Token',{exact:true}).fill('ghp_dummy_native_test_4567');
await page.getByRole('button',{name:'添加 Token',exact:true}).click();
await page.locator('.token-mask').waitFor();
const stored=await ipc('snapshot');
if(stored.catalog.tokens.length!==1 || stored.catalog.tokens[0].masked!=='ghp_********4567')throw Error('Native IPC token roundtrip failed');
await page.getByRole('button',{name:'删除 Token Native smoke',exact:true}).click();
await page.getByRole('button',{name:'确认删除',exact:true}).click();
await page.getByText('还没有添加 GitHub Token').waitFor();
await page.getByRole('button',{name:'全部项目',exact:false}).click();
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'git-sync-native-'));
const repo=path.join(temp,'repository');fs.mkdirSync(repo);
const git=(...args)=>execFileSync('git',['-C',repo,...args],{windowsHide:true,stdio:'pipe'});
git('init','-b','main');git('remote','add','origin','https://github.com/example/native-smoke.git');
await page.getByRole('button',{name:'新增同步',exact:true}).click();
await page.getByLabel('项目名称',{exact:true}).fill('Native project');
await page.getByPlaceholder('选择文件夹或输入新目录的完整路径',{exact:true}).fill(repo);
await page.getByRole('button',{name:'读取仓库信息',exact:false}).click();
await page.getByLabel('远程仓库地址',{exact:true}).waitFor();
await page.waitForFunction(()=>document.querySelector('input[placeholder="https://github.com/用户名/仓库名"]')?.value==='https://github.com/example/native-smoke.git');
await page.getByLabel('保存后启用自动同步').uncheck();
await page.getByRole('button',{name:'创建同步',exact:true}).click();
await page.getByRole('button',{name:'Native project',exact:true}).waitFor();
await page.getByRole('button',{name:'Native project',exact:true}).click();
await page.getByRole('button',{name:'编辑项目',exact:true}).click();
await page.getByLabel('项目名称',{exact:true}).fill('Native renamed');
await page.getByLabel('同步间隔（秒）',{exact:true}).fill('19');
await page.getByRole('button',{name:'保存修改',exact:true}).click();
await page.getByRole('button',{name:'Native renamed',exact:true}).waitFor();
const projectSnapshot=await ipc('snapshot');
if(projectSnapshot.tasks.length!==1 || projectSnapshot.tasks[0].enabled || projectSnapshot.tasks[0].interval_seconds!==19)throw Error('Native task save/edit failed');
await page.getByRole('button',{name:'删除项目',exact:true}).click();
await page.getByRole('button',{name:'确认删除',exact:true}).click();
await page.getByText('从第一个同步项目开始').waitFor();
if(!fs.existsSync(path.join(repo,'.git')))throw Error('Removing task deleted repository');
// Delete only the temporary fixture created above, never an application task path.
if(path.dirname(temp)!==os.tmpdir() || !path.basename(temp).startsWith('git-sync-native-'))throw Error('Unexpected test fixture path');
fs.rmSync(temp,{recursive:true,force:true});
fs.mkdirSync('test-results',{recursive:true});
await page.screenshot({path:'test-results/native-empty.png'});
const after=await ipc('snapshot');
if(after.tasks.length || after.catalog.tokens.length)throw Error('Native test data was not removed');
console.log('Native WebView IPC, task inspect/create/edit/delete, token roundtrip, repository preservation and empty data: passed');
await ipc('exit_app').catch(()=>{});
await browser.close();
